server:
  http_listen_port: 9080
  http_listen_address: 0.0.0.0
    #grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.10.240.122:3100/loki/api/v1/push

scrape_configs:
- job_name: nginxlogs
  static_configs:
  - targets:
    - 10.10.240.122
    labels:
      job: nginxlogs
      __path__: /opt/docker-nginx-php-mysql/var/log/nginx/*.log
